<?php
// Útiles de Escritorio 76-275 — CAP-1490 a CAP-1689
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Modules\Inventario\Models\Familia;
use App\Modules\Inventario\Models\Producto;
use App\Modules\Administracion\Models\Empresa;

class CatalogoParte16Seeder extends Seeder
{
    const START = 1490;

    public function run(): void
    {
        $empresa = Empresa::first();
        if (!$empresa) return;
        $eid = $empresa->id;

        $fid = Familia::withoutGlobalScopes()->where('empresa_id',$eid)->where('codigo','UT-ESC')->value('id');

        $productos = [
            ['ESCRITORIO DE MADERA','UND'],
            ['ESCRITORIOS','UND'],
            ['ESCUADRA','UND'],
            ['ESPIRAL PARA ANILLADO','UND'],
            ['ESPIRALES N°16 PARA PARA ANILLADO','UND'],
            ['ESPONJERO','UND'],
            ['ESTABILIZADOR DE ENERGIA FORZA','UND'],
            ['ESTANTE','UND'],
            ['ESTANTES','UND'],
            ['ESTILETE','UND'],
            ['ESTILETE TRUPER','UND'],
            ['ESTUFA','UND'],
            ['EXTENSION','UND'],
            ['EXTENSIÓN X5MT','UND'],
            ['FASTER','UND'],
            ['FASTER ARTESCO','CJA'],
            ['FASTER PARA ARCHIVADOR','UND'],
            ['FASTER X50','CJA'],
            ['FOLDER MANILA','UND'],
            ['FOLDER MANILA A4 X25','PQTE'],
            ['FOLDER MANILA AMARILLO','UND'],
            ['FUENTE DE ENERGIA ESCANER CANON C357IF','UND'],
            ['GLOBO CARNAVAL','UND'],
            ['GOMA EN BARRA','UND'],
            ['GOMA EN BARRA CH','UND'],
            ['GOMA EN BARRA MED','UND'],
            ['GORRA NAVIDEÑA','UND'],
            ['GORRA NAVIDEÑA LENTEJUELA','UND'],
            ['GORRA NAVIDEÑA SIMPLE','UND'],
            ['GRAPAS ARTESCO','CJA'],
            ['GRAPAS X1000','CJA'],
            ['GRAPAS X5000','CJA'],
            ['GREPE','UND'],
            ['GUANTES BLANCOS','UND'],
            ['GUIRNALDA','UND'],
            ['GUIRNALDA NAVIDEÑA','UND'],
            ['HERVIDORA OSTER','UND'],
            ['HERVIDORA PLOMO','UND'],
            ['HOJA BOND','PQTE'],
            ['HOJA BOND A3','UND'],
            ['HOJA BOND A4','PQTE'],
            ['HOJA DE COLOR','UND'],
            ['HOJA DE COLORES','PQTE'],
            ['HOJAS DE COLOR','UND'],
            ['HUELLERO','UND'],
            ['HUELLERO ARTESCO','UND'],
            ['IMPRESORA CANON 64110','UND'],
            ['IMPRESORA CANON G3110','UND'],
            ['IMPRESORA EPSON L495 X2PE028031','UND'],
            ['IMPRESORA L3250','UND'],
            ['INFLADOR','UND'],
            ['JERINGA PARA TINTE','UND'],
            ['JUEGO DE REGLA 30CM','PQTE'],
            ['KIT DE DECORACIÓN CON GLOBOS','UND'],
            ['LAMINAS DE ENMICAR X100','PQTE'],
            ['LAMINAS DE MICA PARA FOTOCHEK','UND'],
            ['LAMINAS PARA ENMICAR X100','PQTE'],
            ['LAPICERO AZUL FC','UND'],
            ['LAPICERO DE COLORES AM/AN/CL/VR/MN','UND'],
            ['LAPICERO FC AZUL','UND'],
            ['LAPICERO FC ROJO','UND'],
            ['LAPICERO NEGRO FC','UND'],
            ['LAPICERO ROJO','UND'],
            ['LAPICERO ROJO FC','UND'],
            ['LAPIZ 2B ARTESCO','UND'],
            ['MAQUINA DE SELLO AUTOMATICO','UND'],
            ['MAQUINA PARA SELLOS AUTOMATICOS','UND'],
            ['MASKING 2"','UND'],
            ['MESA DE MADERA','UND'],
            ['MESA HECHIZA','UND'],
            ['MICA A4 X10','PQTE'],
            ['MICA PARA AN ILLADO','PAR'],
            ['MICA PARA FOTOCHEK','UND'],
            ['MICAS A4','PQTE'],
            ['MINI ENGRAPADOR','UND'],
            ['MINI PERFORADOR','UND'],
            ['MODEM TP LINK','UND'],
            ['MODEM ZTEMF920V','UND'],
            ['MONITOR LG 20M47A-B','UND'],
            ['MONITOR SAMSUMG MODELO L520D300NH/PE','UND'],
            ['MOTA','UND'],
            ['MOUSE GENIUS','UND'],
            ['PALIGLOBO DELGADO BLANCO','UND'],
            ['PAPEL BOND X500','PQTE'],
            ['PAPEL DE REGALO SURTIDO','UND'],
            ['PAPEL FOTOGRÁFICO X20','PQTE'],
            ['PAPEL LUSTER AZUL','UND'],
            ['PAPEL LUSTRE AZUL','UND'],
            ['PAPEL LUSTRE CELESTE','UND'],
            ['PAPEL TERMICO PARA CARMIX','ROL'],
            ['PAPELOTE CUADRICULADO','UND'],
            ['PAPELOTE CUDRICULADO','UND'],
            ['PELUCA PAYASO DE COLOR','UND'],
            ['PERCHERO','UND'],
            ['PERFORADOR','UND'],
            ['PERFORADOR ARTESCO','UND'],
            ['PILA 2A OPALUX RECARGABLE','PAR'],
            ['PILA 3A DURACELL','PAR'],
            ['PILA DURACELL 2A','PAR'],
            ['PILA DURACELL 3A','PAR'],
            ['PILA PANASONIC 2A','PAR'],
            ['PILAS D2','PAR'],
            ['PIZARRA 1.20X80','UND'],
            ['PIZARRA 1.60X1.20','UND'],
            ['PIZARRA 20X40','UND'],
            ['PIZARRA 35X50','UND'],
            ['PIZARRA 50X60','UND'],
            ['PIZARRA ACRILICA 1.20X80','UND'],
            ['PIZARRA ACRILICA 40X30','UND'],
            ['PIZARRA ACRILICA 60X40','UND'],
            ['PIZARRA ACRILICA 60X80','UND'],
            ['PLUMON INDELEBLE DEL NG','UND'],
            ['PLUMON INDELEBLE DEL RJ','UND'],
            ['PLUMON INDELEBLE DELGADO AZUL','UND'],
            ['PLUMON INDELEBLE DELGADO NEGRO','UND'],
            ['PLUMON PAPELOTE MN','UND'],
            ['PLUMON PAPELOTE NG','UND'],
            ['PLUMON PAPELOTE RJ','UND'],
            ['PLUMON PAPELOTE VR','UND'],
            ['PLUMON PARA PAPELOTE NG','UND'],
            ['PLUMON PARA PAPELOTE RJ','UND'],
            ['PLUMON PARA PAPELOTE VR','UND'],
            ['PLUMON PARA PIZARRA NG','UND'],
            ['PLUMON PARA PIZARRA RJ','UND'],
            ['PLUMON PIZARRA ACRIMAX AZUL','UND'],
            ['PLUMON PIZARRA ACRIMAX NG','UND'],
            ['PLUMON PIZARRA ACRIMAX ROJO','UND'],
            ['PLUMON PIZARRA ACRIMAX VERDE','UND'],
            ['PLUMON PIZARRA AZUL','UND'],
            ['PLUMON PIZARRA NEGRO','UND'],
            ['PLUMON PIZARRA ROJO','UND'],
            ['POLO DIA DEL MINERO','UND'],
            ['PONCHO NAVIDEÑO','UND'],
            ['PORTA CLIPS','UND'],
            ['POSIT','PQTE'],
            ['PROTECTOR DE TECLADO','UND'],
            ['PROYECTOR MULTIMEDIA EPSON WDRF6Z1891L','UND'],
            ['REGLA 20CM','UND'],
            ['REGLA 30CM','UND'],
            ['REGLA DE 30 CM','UND'],
            ['REGLA METALICA 50CM','UND'],
            ['RENDICION DE GASTOS','TAL'],
            ['REPORTE DE ACTOS Y CONDICIÓN','TAL'],
            ['RESALTADOR AMARILLO','UND'],
            ['RESALTADOR AMARILLO ARTESCO','UND'],
            ['RESALTADOR ARTESCO','UND'],
            ['ROUTE DIXON BA1312007002823','UND'],
            ['ROUTER INTERNET','UND'],
            ['ROUTER OPTICTIMES XPONUNU2X8404DW','UND'],
            ['SACAGRAPA','UND'],
            ['SACRAGRAPA','UND'],
            ['SELLO AUTOMATICO ALMACEN HUACHOCOLPA','UND'],
            ['SELLO AUTOMATICO JHON DE LA CRUZ HUAMANI','UND'],
            ['SELLO AUTOMATICO RECIBIDO','UND'],
            ['SEPARADORES','PQTE'],
            ['SILBATO NEGRO','UND'],
            ['SILBATOS','UND'],
            ['SILICONA LIQUIDA 250ML','UND'],
            ['SILICONA LIQUIDA ARTESCO','UND'],
            ['SILLA DE PLASTICO BLANCO GENPLAST','UND'],
            ['SILLA DE PLASTICO BLANCO REY','UND'],
            ['SILLA GIRATORIA','UND'],
            ['SILLAS ESTACIONARIAS','UND'],
            ['SILLAS ESTATICAS','UND'],
            ['SILLAS GIRATORIAS','UND'],
            ['SOBRE MANILA','UND'],
            ['SOBRE MANILA A3 RADIOGRAFICO X50','PQTE'],
            ['SOBRE MANILA A4 X50','PQTE'],
            ['SOMBRERO DE BRUJA','UND'],
            ['SUPRESOR DE 6 TOMAS','UND'],
            ['TABLERO A4','UND'],
            ['TABLEROS A4 MADERA','UND'],
            ['TABLEROS A4 PLASTIFICADO','UND'],
            ['TACHO RR.SS','UND'],
            ['TAJADOR','UND'],
            ['TAMPON','UND'],
            ['TECLADO LOGITECH 2153MROE2F38','UND'],
            ['TECLADO LOGITEVH KEYBOARD K120','UND'],
            ['TERMORADIADOR IMACO','UND'],
            ['THERMO HERVIDOR 5.8LT','UND'],
            ['THERMO PLASTICO','UND'],
            ['THERMO SIFON FACUSA','UND'],
            ['TIJERA ARTESCO','UND'],
            ['TIJERA ARTESCO ANARANJADO','UND'],
            ['TIJERA ARTESCO GR','UND'],
            ['TINTA EPSON AZUL 70ML','UND'],
            ['TINTA PARA IMPRESORA 1L AM','LT'],
            ['TINTA PARA IMPRESORA 1L AZ','LT'],
            ['TINTA PARA IMPRESORA 1L MAGENTA','LT'],
            ['TINTA PARA IMPRESORA 1L NG','LT'],
            ['TINTA PARA IMPRESORA AMARILLO','LT'],
            ['TINTA PARA IMPRESORA CELESTE','LT'],
            ['TINTA PARA IMPRESORA MAGENTA','LT'],
            ['TINTA PARA IMPRESORA NEGRO','LT'],
            ['TINTA PARA TAMPON','UND'],
            ['TIZA BLANCA','UND'],
            ['VALE DE SALIDA DE ALMACEN','TAL'],
            ['VINCHA GRINCH','UND'],
            ['VINCHA NAVIDEÑA','UND'],
            ['VINIFAN OFICIO','UND'],
        ];

        foreach ($productos as $i => [$nombre, $unidad]) {
            $codigo = 'CAP-' . str_pad(self::START + $i, 4, '0', STR_PAD_LEFT);
            Producto::withoutGlobalScopes()->firstOrCreate(
                ['empresa_id' => $eid, 'codigo' => $codigo],
                ['nombre' => $nombre, 'familia_id' => $fid, 'unidad_medida' => $unidad, 'activo' => true, 'stock_minimo' => 0, 'stock_maximo' => 0]
            );
        }
        $this->command->info('Parte 16 — Útiles de Escritorio 76-275: ' . count($productos) . ' productos.');
    }
}
